name: swissimages
favicon: null
layout_spectrum: 1
typography_spectrum: 0.28482
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dee2db'
    - '#88a0c0'
    - '#495d10'
    - '#15200c'
    - '#9cb024'
  brandStrength: 0.6945452934596688
  lightness: 0.4113443864043802
  saturation: 0.4482535265851766
  rhythmicContrast: 0.8441898843739182
purpose: []
